Repository MOD-Magazine/MOD-Magazine, pull requests merged in 2023-05, with the labels that each got.

#19 Add CI for formatting
  .github/CODEOWNERS
  .github/actions/setup/action.yml
  .github/workflows/check-format.yml
  .github/workflows/fix-format.yml
  April23/assets/ATTRIBUTION.md
  April23/flashfest.md
  CONTRIBUTING.md
  README.md
  article-template.md
Labels: meta

#12 feat: factor out contributing guidelines to their own file, update them
  CONTRIBUTING.md
Labels: meta

#21 article: flashfest expansion
  .github/workflows/check-format.yml
  April23/assets/constant_jeb_cow.png
  April23/assets/emotecraft.png
  April23/assets/free_trades.png
  April23/assets/tiny_gender.png
  April23/assets/unobtanium.png
  April23/flashfest.md
Labels: mc content

#18 article: call for volunteers
  April23/call-for-volunteers.md
Labels: meta

#22 article: update cycle
  April23/update-cycle.md
Labels: minecraft/mojang

#20 article: curseforge drama
  April23/curseforge-title-tbd.md
Labels: minecraft/mojang
